name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-alpine-linux-x86:
    name: test alpine linux on x86
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        arch: x86
        extra-repositories: http://dl-cdn.alpinelinux.org/alpine/edge/community
        packages: curl build-base sudo coreutils
    - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
      shell: alpine.sh {0}
    - run: sh rustup.sh -y --profile minimal --default-toolchain nightly
      shell: alpine.sh {0}
    - run: $HOME/.cargo/bin/cargo test --verbose -- --nocapture
      shell: alpine.sh {0}
      env:
        RUST_BACKTRACE: full
