name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-alpine-linux-x86:
    name: test alpine linux on x86
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: jirutka/setup-alpine@v1
      with:
        branch: v3.15
        arch: x86
        packages: rust cargo build-base
    - run: cargo test --verbose -- --nocapture
      shell: alpine.sh {0}
      env:
        RUST_BACKTRACE: full
